nelmio_api_doc:
    documentation:
        info:
            title: Sanctuary API
            description: Documentation for Sanctuary API
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/v1
